// App
import type { NextPage } from 'next';
import Head from 'next/head';

// Components
import RootLayout from '../app/layout';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Cryptonite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <RootLayout /> */}
    </>
  );
};

export default Home;
