// App
import type { NextPage } from 'next';
import Head from 'next/head';

// Components
import Header from '../components/layout/Header/Header';

const Home: NextPage = () => {
  return (
    <html>
      <Head>
        <title>Cryptonite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Header />
      </body>
    </html>
  );
};

export default Home;
